###==========================================================================================###
## 部署
#  重要的外部参数
#  --eureka.client.service-url.defaultZone="http://192.168.0.166:8761/eureka/,http://192.168.0.166:8762/eureka/"
#  --spring.cloud.config.label
#  --spring.cloud.config.profile
#  --eureka.instance.ip-address
#
#  可选的外部参数
#  -Dspring.cloud.inetutils.preferredNetworks=192.168.0
#  --spring.profiles.active=fast-discovery
#
#  例子
#  --eureka.instance.ip-address=192.168.0.164
#  --eureka.client.service-url.defaultZone="http://192.168.0.166:8761/eureka/"
#  --spring.cloud.config.label=laptop
#  --spring.cloud.config.profile=dev
#  --spring.profiles.active=dev,fast-discovery
#
###==========================================================================================###
server:
  port: 18900

logging:
  level:
    #org.springframework.cache: DEBUG
    #org.asynchttpclient: DEBUG
    org.springframework.amqp.rabbit: INFO
    #me.shufork.biz.mq.consumer: TRACE

info:
  version: '@project.version@'

liquibase:
  change-log: classpath:db/changelog/changelog.xml
  #default-schema: db_coc_war
  #drop-first: false
  #enabled: true

coc.war-log.auto-load: true

spring:
  jpa:
    hibernate:
      ddl-auto: none # TODO: set to none
  cloud:
#    inetutils:
#      preferredNetworks: # TODO : overwrite
#        - 192.168
#        - 10.11
    stream:
      default:
        content-type: application/json
      bindings:
        coc_clan_found_output:
          binder: rabbit
          destination: clanFound
          #producer:
          #  required-groups: tracker
        coc_war_log_loaded_input:
          binder: rabbit
          destination: warLogLoaded
          group: default
        coc_war_log_rejected_input:
          binder: rabbit
          destination: warLogRejected
          group: default
      rabbit:
        bindings:
          coc_war_log_loaded_input:
            consumer:
              acknowledgeMode: AUTO
              durableSubscription: true
              prefetch: 1
              requeueRejected: true
              autoBindDlq: true
              republishToDlq: true
              dlqMaxLength: 1000
          coc_war_log_rejected_input:
            consumer:
              acknowledgeMode: AUTO
              durableSubscription: true
              prefetch: 1
              requeueRejected: false
              autoBindDlq: false
              republishToDlq: false
              dlqMaxLength: 100

---
spring:
  profiles: dev

---
spring:
  profiles: test

---
spring:
  profiles: fast-discovery

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
